Repository cornell-dti/course-plan, pull requests merged in 2022-11, with the labels that each got.

#751 Create Progress Tracker Tool Card
  src/assets/images/progress_tracker/confetti.svg
  src/assets/images/progress_tracker/fire.svg
  src/assets/images/progress_tracker/flex.svg
  src/assets/images/progress_tracker/hands_raised.svg
  src/assets/images/progress_tracker/star.svg
  src/components/Tools/ProgressTracker.vue
  src/containers/Tools.vue
  src/requirement-types.d.ts
  src/utilities.ts
Labels: front-end

#760 Quick Touch Up to Tools Page
  src/components/Tools/Card.vue
  src/components/Tools/ProgressTracker.vue
  src/components/Tools/UsefulLinks.vue
  src/containers/Tools.vue
Labels: small, front-end

#754 Create workflow to backup Firestore
  .github/workflows/backup-firestore.yml
Labels: util
